WikiCamp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^wiki/', include('wiki.urls', namespace="wiki")),
    url(r'^admin/', include(admin.site.urls)),
]

wiki/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # # ex: /polls/5/vote/
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

wiki/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    question_text = models.CharField(max_length="200")
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    def __str__(self):
        return self.choice_text

    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

wiki/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

# Create your views here.


class IndexView(generic.ListView):
    template_name = 'wiki/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions. (not included those set to be published in the future)"""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    #__lte_ less then or equal, en este case : menor o igual al dia de hoy


class DetailView(generic.DetailView):
    model = Question
    template_name = 'wiki/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'wiki/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'wiki/detail.html', {
            'question': p,
            'error_message': "You didnt select a choice.", })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('wiki:results', args=(p.id,)))



################# Primera parte del tutorial las vistas sin usar generic views #####################
#
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'wiki/index.html', context)


# def detail(request, question_id):
#     # try:
#     #     question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404("Question does not exist")
#     # return render(request, 'wiki/detail.html', {'question': question})
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'wiki/detail.html', {'question': question})


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "wiki/results.html", {'question': question})

wiki/templates/wiki/detail.html
<h1>{{ question.question_text}}</h1>

{% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'wiki:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}	
	<input type="radio" name="choice" id="choice{{ forloop.counter}}" value="{{ choice.id}}"/>
	<label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label><br />
	{% endfor %} <br />
	<input type="submit" value="Vote">
</form>

wiki/templates/wiki/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
<ul>
	{% for question in latest_question_list %}
	<li><a href="{% url 'wiki:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

wiki/templates/wiki/results.html
<h1>{{ question.question_text }}</h1>

<ul>
	{% for choice in question.choice_set.all %}
		<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
	{% endfor %}
</ul>
<a href="{% url 'wiki:detail' question.id %}">Vote again?</a>